---
n8n_container_name: n8n
n8n_image: docker.n8n.io/n8nio/n8n
n8n_port: 5678
n8n_volume_name: n8n_data
n8n_restart_policy: unless-stopped
n8n_health_check_retries: 20
n8n_health_check_delay: 5
n8n_owner_email: "test@example.com"
n8n_owner_password: "TestPassword123!"
n8n_owner_first_name: "Test"
n8n_owner_last_name: "User"
