---
outline_image: "outlinewiki/outline:0.82.0"
outline_postgres_image: "postgres:16-alpine"
outline_redis_image: "valkey/valkey:8.0-alpine"

outline_port: 3001
outline_data_dir: /opt/outline
outline_container_name: outline
outline_hostname: "outline"
outline_bind_address: "127.0.0.1"
outline_public_url: ""
outline_restart_policy: unless-stopped
outline_health_check_retries: 30
outline_health_check_delay: 10
outline_timezone: "Europe/Warsaw"
