---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/../../../../../../requirements.yml
driver:
  name: delegated
  options:
    managed: true
platforms:
  - name: mergerfs-qemu-test
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ../../
  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
  inventory:
    host_vars:
      mergerfs-qemu-test:
        ansible_host: 127.0.0.1
        ansible_port: 2222
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /tmp/molecule-qemu/id_rsa
        ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/tmp/molecule-qemu/known_hosts"
verifier:
  name: testinfra
  options:
    v: true
