---
paperless_container_name: paperless
paperless_image: "ghcr.io/paperless-ngx/paperless-ngx:2.14.7"
paperless_port: 8000
paperless_data_dir: /opt/paperless
paperless_document_path: ""
paperless_redis_image: "redis:7.4"
paperless_postgres_image: "postgres:16.6"
paperless_restart_policy: unless-stopped
paperless_health_check_retries: 20
paperless_health_check_delay: 10
paperless_hostname: "paperless"
paperless_bind_address: "127.0.0.1"
paperless_public_url: ""
