[masternode]
master ansible_host=192.168.1.1 ansible_user=YOUR_USER ansible_become=true

[workers]
# worker-1 ansible_host=ASSIGNED_VIA_DHCP ansible_user=YOUR_USER ansible_become=true
# worker-2 ansible_host=ASSIGNED_VIA_DHCP ansible_user=YOUR_USER ansible_become=true
# worker-3 ansible_host=ASSIGNED_VIA_DHCP ansible_user=YOUR_USER ansible_become=true

[lab:children]
masternode
workers
