---
ansible_user: root
docker_data_dir: /opt/homelab
docker_network_name: homelab-net
public_ip: "127.0.0.1"
wireguard_password: "test-password-molecule"
wireguard_port: 51820
wireguard_web_port: 51821
wireguard_dns: "1.1.1.1"
wireguard_mtu: 1420
wireguard_persistent_keepalive: 25
wireguard_container_name: wg-easy
wireguard_data_dir: "{{ docker_data_dir }}/wireguard"
wireguard_image: "ghcr.io/wg-easy/wg-easy:14"
