---
kubeconfig_local_path: "{{ lookup('env', 'HOME') }}/.kube/lw-c1.yaml"
vcluster_namespace: "test"
vcluster_name: "test-cluster"
vcluster_chart_version: "0.20.0"
vcluster_k3s_image: "rancher/k3s:v1.30.2-k3s1"
vcluster_ready_retries: 20
vcluster_ready_delay: 10
