# i3-setup/roles/packages/tasks/main.yml
---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  become: true
