---
seafile_container_name: seafile
seafile_image: seafileltd/seafile-mc:11.0
seafile_port: 8080

seafile_db_container_name: seafile-db
seafile_db_image: mariadb:10.11
seafile_db_root_password: ""

seafile_memcached_container_name: seafile-memcached
seafile_memcached_image: memcached:1.6-alpine

seafile_admin_email: ""
seafile_admin_password: ""
seafile_data_path: ""

seafile_compose_dir: /opt/seafile

seafile_health_check_retries: 20
seafile_health_check_delay: 10
