---
seafile_container_name: seafile
seafile_image: seafileltd/seafile-mc:11.0
seafile_port: 8080
seafile_data_path: ""

seafile_db_container_name: seafile-db
seafile_db_image: mariadb:10.11

seafile_memcached_container_name: seafile-memcached
seafile_memcached_image: memcached:1.6-alpine

caddy_container_name: seafile-caddy
caddy_image: caddy:2-alpine
caddy_domain: ""

seafile_compose_dir: /opt/seafile
seafile_hostname: "seafile"
